version: '3.7'

services:
  
  dockersuperagent1:
    hostname: dockersuperagent1
    image: scopeinfra/azuredevops-linux-agent-auth-negotiate:jdk17-jdk11-jdk8-mvn3.8-nodejs16-py3-go1.17-dockercli-buildah-sonarscanner4.6-azp2.181.2
    container_name: dockersuperagent1
    restart: unless-stopped
    volumes:
      # Maven settings.xml mount operation:
      - './inits/settings.xml:/root/.m2/settings.xml'
      # Sonar Scanner properties file mount operation:
      - './inits/sonar-scanner.properties:/azp/sonarscanner/sonar-scanner-4.6.2.2472-linux/conf/sonar-scanner.properties'
      # Access Docker socket inside the Docker Container.
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      # Software Tools Env Definitions:
      - "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/"
      - "GOPATH=/azp/go/workspace"
      - "M2_HOME=/usr/share/maven"
      # Azure DevOps Agent Env Definitions:
      - "AZP_URL=http://domain.company.com.tr:8080/tfs/collection_name/"
      - "AZP_POOL=Default"
      - "AZP_USERNAME=username"
      - "AZP_PASSWORD=password"
      - "AZP_TOKEN=token"
      - "AZP_WORK=_work"
  